services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml:ro
      - prometheus-data:/prometheus
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alert-manager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/alertmanager
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
     - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
  mailhog:
    container_name: mailhog
    image: mailhog
    ports:
      - 8025:8025

volumes:
  prometheus-data:
  alertmanager-data:
  grafana-data: